ADMIN_EMAIL=nexasphere@glbajajgroup.org
ADMIN_PASSWORD=Admin@123
CORS_ORIGIN=http://localhost:5173,http://localhost:5174,http://localhost:5175

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nexasphere}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:}

spring.h2.console.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.port=8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10MB

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
