filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata: ~

  - type: log
    enabled: true
    paths:
      - '/var/log/nexasphere/*.log'
    fields:
      service: nexasphere-api
    fields_under_root: false
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message

output.logstash:
  hosts: ['logstash:5044']

logging.level: info
logging.to_files: false
