input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ /^\{.*\}$/ {
    json {
      source => "message"
      target => "nexa"
    }
    mutate {
      rename => {
        "[nexa][timestamp]" => "@timestamp"
        "[nexa][level]" => "level"
        "[nexa][message]" => "log_message"
        "[nexa][service]" => "service"
        "[nexa][reqId]" => "reqId"
        "[nexa][traceId]" => "traceId"
        "[nexa][userId]" => "userId"
      }
    }
  }

  if [log_message] {
    mutate {
      replace => { "message" => "%{log_message}" }
    }
  }

  if ![service] {
    mutate { add_field => { "service" => "unknown" } }
  }
}

output {
  if [level] == "audit" or [level] == "admin" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "nexasphere-compliance-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "nexasphere-logs-%{+YYYY.MM.dd}"
    }
  }
}
