input {
  beats {
    port => 5044
  }

  file {
    path => "/var/log/nexasphere/api-requests.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    tags => ["api-requests"]
  }
}

filter {
  if "api-requests" in [tags] {
    json {
      source => "message"
    }
    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }
    mutate {
      remove_field => ["message"]
    }
  } else if [message] =~ /^\{.*\}$/ {
    json {
      source => "message"
      target => "nexa"
    }
    mutate {
      rename => {
        "[nexa][timestamp]" => "@timestamp"
        "[nexa][level]" => "level"
        "[nexa][message]" => "log_message"
        "[nexa][service]" => "service"
        "[nexa][reqId]" => "reqId"
        "[nexa][traceId]" => "traceId"
        "[nexa][userId]" => "userId"
      }
    }
  }

  if [log_message] {
    mutate {
      replace => { "message" => "%{log_message}" }
    }
  }

  if ![service] {
    mutate { add_field => { "service" => "unknown" } }
  }

  if [level] == "error" or ([status] and [status] >= 500) {
    mutate {
      add_field => { "alert" => "true" }
    }
  }
}

output {
  if [level] == "audit" or [level] == "admin" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "nexasphere-compliance-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "nexasphere-logs-%{+YYYY.MM.dd}"
    }
  }
}
