global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: nexasphere-api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8787']
        labels:
          service: nexasphere-api

  - job_name: nexasphere-python
    metrics_path: /metrics
    static_configs:
      - targets: ['python-api:8000']
        labels:
          service: nexasphere-python

  - job_name: nexasphere-java
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: nexasphere-java

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter:9121']
