export const whiteboardTemplates = {
  kanban: {
    elements: [
      {
        id: 'template-kanban-col-1',
        type: 'sticky',
        x: 60,
        y: 60,
        w: 220,
        h: 140,
        color: '#fbbf24',
        opacity: 1,
        fill: '#fbbf24',
        text: 'To Do\n\n• Item 1\n• Item 2',
        fontSize: 14,
      },
      {
        id: 'template-kanban-col-2',
        type: 'sticky',
        x: 360,
        y: 60,
        w: 220,
        h: 140,
        color: '#60a5fa',
        opacity: 1,
        fill: '#60a5fa',
        text: 'In Progress\n\n• Task A\n• Task B',
        fontSize: 14,
      },
      {
        id: 'template-kanban-col-3',
        type: 'sticky',
        x: 660,
        y: 60,
        w: 220,
        h: 140,
        color: '#34d399',
        opacity: 1,
        fill: '#34d399',
        text: 'Done\n\n• Completed',
        fontSize: 14,
      },
    ],
  },
  mindmap: {
    elements: [
      {
        id: 'template-mindmap-center',
        type: 'sticky',
        x: 430,
        y: 280,
        w: 260,
        h: 140,
        color: '#f472b6',
        opacity: 1,
        fill: '#f472b6',
        text: 'Mind Map\n\nCentral Idea',
        fontSize: 14,
      },
      {
        id: 'template-mindmap-line-1',
        type: 'arrow',
        x: 540,
        y: 350,
        w: 260,
        h: -180,
        color: '#a855f7',
        opacity: 0.9,
        strokeWidth: 5,
      },
      {
        id: 'template-mindmap-note-1',
        type: 'sticky',
        x: 760,
        y: 110,
        w: 220,
        h: 120,
        color: '#60a5fa',
        opacity: 1,
        fill: '#60a5fa',
        text: 'Branch 1',
        fontSize: 14,
      },
    ],
  },
  flowchart: {
    elements: [
      {
        id: 'template-flow-start',
        type: 'rect',
        x: 140,
        y: 170,
        w: 280,
        h: 130,
        color: '#60a5fa',
        opacity: 0.9,
        strokeWidth: 4,
        fill: 'rgba(96,165,250,0.15)',
      },
      {
        id: 'template-flow-arrow-1',
        type: 'arrow',
        x: 300,
        y: 240,
        w: 280,
        h: 0,
        color: '#a855f7',
        opacity: 0.9,
        strokeWidth: 5,
      },
      {
        id: 'template-flow-step',
        type: 'rect',
        x: 440,
        y: 170,
        w: 280,
        h: 130,
        color: '#a855f7',
        opacity: 0.9,
        strokeWidth: 4,
        fill: 'rgba(168,85,247,0.15)',
      },
    ],
  },
  swot: {
    elements: [
      {
        id: 'template-swot',
        type: 'sticky',
        x: 320,
        y: 120,
        w: 460,
        h: 330,
        color: '#fbbf24',
        opacity: 1,
        fill: '#fbbf24',
        text: 'SWOT\n\nStrengths\nWeaknesses\nOpportunities\nThreats',
        fontSize: 14,
      },
    ],
  },
  leanCanvas: {
    elements: [
      {
        id: 'template-lean',
        type: 'sticky',
        x: 260,
        y: 120,
        w: 560,
        h: 330,
        color: '#34d399',
        opacity: 1,
        fill: '#34d399',
        text: 'Lean Canvas\n\nProblem\nSolution\nKey Metrics\nUnique Value',
        fontSize: 14,
      },
    ],
  },
};
